# Generated by Django 4.2.22 on 2025-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Om meg-tekst")),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Navn")),
                ("email", models.EmailField(max_length=254, verbose_name="E-post")),
                ("subject", models.CharField(max_length=200, verbose_name="Emne")),
                ("message", models.TextField(verbose_name="Melding")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sendt"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=200, verbose_name="Skole")),
                (
                    "degree",
                    models.CharField(max_length=200, verbose_name="Grad / Utdanning"),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=200, verbose_name="Studieretning"),
                ),
                ("start_date", models.DateField(verbose_name="Startdato")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Sluttdato"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivelse"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, verbose_name="Stilling"),
                ),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Arbeidsgiver"),
                ),
                ("start_date", models.DateField(verbose_name="Startdato")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Sluttdato"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivelse"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Prosjekttittel"),
                ),
                ("description", models.TextField(verbose_name="Beskrivelse")),
                ("link", models.URLField(blank=True, verbose_name="Lenke")),
                ("date", models.DateField(verbose_name="Dato")),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ferdighet")),
                (
                    "level",
                    models.CharField(blank=True, max_length=100, verbose_name="Nivå"),
                ),
            ],
        ),
    ]
